plugins:
  - jekyll-avatar
  - jekyll-remote-theme

## try to fix (auto-) update errors (lock in version), see
##   https://twitter.com/mmistakes/status/1048190447976423425
remote_theme: "mmistakes/minimal-mistakes@4.13.0"

title: Ruby Habits
logo: /assets/images/logo.png

header:
  image: /assets/images/banner_transparent.png
  image_description: "Ruby Habits Logo"

minimal_mistakes_skin: "sunrise"

exclude:
  - README.md
  - LICENSE
